[Log]
Level = "INFO"
Environment = "development"
Outputs = ["stderr"]

[SyncDB]
Database = "postgres"
User = "{{.bridge_db.user}}"
Name = "{{.bridge_db.name}}"
Password = "{{.bridge_db.password}}"
Host = "{{.bridge_db.hostname}}"
Port = "{{.bridge_db.port}}"
MaxConns = 20

[Etherman]
l1URL = "{{.l1_rpc_url}}"
L2URLs = ["{{.rpc_rpc}}"]

[Synchronizer]
SyncInterval = "5s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "{{.bridge_port}}"
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
    # Read only
    [BridgeServer.DB]
    Database = "postgres"
    User = "{{.bridge_db.user}}"
    Name = "{{.bridge_db.name}}"
    Password = "{{.bridge_db.password}}"
    Host = "{{.bridge_db.hostname}}"
    Port = "{{.bridge_db.port}}"
    MaxConns = 20

[NetworkConfig]
GenBlockNumber = 0
PolygonBridgeAddress = "{{.bridgeAddress}}"
PolygonZkEVMGlobalExitRootAddress = "{{.gerAddress}}"
PolygonRollupManagerAddress = "{{.rollupAddress}}"
PolygonZkEVMAddress = "{{.zkevmAddress}}"
L2PolygonBridgeAddresses = ["{{.bridgeAddress}}"]

[ClaimTxManager]
FrequencyToMonitorTxs = "5s"
PrivateKey = {Path = "/config/claimtxmanager.keystore", Password = "{{.claimtxmanager_keystore_password}}"}
Enabled = true
RetryInterval = "1s"
RetryNumber = 10