PrivateKey = {Path = "/config/dac.keystore", Password = "{{.dac_keystore_password}}"}

[L1]
RpcURL = "{{.l1_rpc_url}}"
PolygonValidiumAddress = "{{.zkevmAddress}}" #POE/ZKEVM ADDR
DataCommitteeAddress = "{{.polygonDataCommitteeAddress}}"
Timeout = "1m"
RetryPeriod = "5s"
BlockBatchSize = "64"
GenesisBlock = "0"
TrackSequencer = false

[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[DB]
User = "{{.dac_db.user}}"
Password = "{{.dac_db.password}}"
Name = "{{.dac_db.name}}"
Host = "{{.dac_db.hostname}}"
Port = {{.dac_db.port}}
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = {{.dac_port}}
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
