[Log]
Environment = "development"
Level = "INFO"
Outputs = ["stdout"]

[Server]
Host = "0.0.0.0"
Port = {{.pm_port}}
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
EnableHttpLog = true
BatchRequestsEnabled = false
BatchRequestsLimit = 20

[DB]
Name = "{{.pm_db.name}}"
User = "{{.pm_db.user}}"
Password = "{{.pm_db.password}}"
Host = "{{.pm_db.hostname}}"
Port = {{.pm_db.port}}
EnableLog = false
MaxConns = 200

[Sender]
SequencerURL = "{{.sequencer_rpc}}"
ResendTxsCheckInterval = "5s"
Workers = 8
QueueSize = 25

[Monitor]
L2NodeURL = "{{.rpc_rpc}}"
Workers = 8
QueueSize = 25
RetryWaitInterval = "3s"
InitialWaitInterval = "3s"
TxLifeTimeMax = "300s"
